export const SET_TOKEN = "SET_TOKEN";

export const SET_RIDE_MODE = "SET_RIDE_MODE";

export const SET_REGIONS = "SET_REGIONS";

export const SET_ROLE_LIST = "SET_ROLE_LIST";

export const SET_ROLE_ID = "SET_ROLE_ID";

export const SET_SELECTED_DROPDOWN = "SET_SELECTED_DROPDOWN";

export const SET_USER_TYPE = "SET_USER_TYPE";

export const SET_PERMISSIONS = "SET_PERMISSIONS";

export const SET_REGION_CENTER = "SET_REGION_CENTER";

export const SET_REGION_BOUNDARY = "SET_REGION_BOUNDARY";
export const UPDATE_IMAGE_VIEWER = "UPDATE_IMAGE_VIEWER";

export const SHOW_MESSAGE = "SHOW_MESSAGE";
export const HIDE_MESSAGE = "HIDE_MESSAGE";
